# Exemplo de arquivo secrets.toml para Streamlit Cloud
# Copie este arquivo e configure com suas credenciais reais

[google_sheets]
type = "service_account"
project_id = "seu-project-id"
private_key_id = "sua-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nsua-private-key-aqui\n-----END PRIVATE KEY-----\n"
client_email = "seu-service-account@seu-project.iam.gserviceaccount.com"
client_id = "seu-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "sua-cert-url"

# Configurações da aplicação
INVENTORY_SPREADSHEET_ID = "1IMcXLIyOJOANhfxKfzYlwtBqtsXJfRMhCPmoKQdCtdY"
MONITORS_SPREADSHEET_ID = "1hI6WWiH03AvXFxMCpPpYtIhQEU062C_k4utIE6YyctY"

# JIRA
JIRA_BASE_URL = "https://nubank.atlassian.net"
JIRA_EMAIL = "seu-email@empresa.com"
JIRA_API_TOKEN = "seu-token-jira"
JIRA_PROJECT_KEY = "TS"
